### ISSUE TITLE
node-pdfium project building failed.

### ISSUE THREAD

**Issue by kamaldeepoodles** [tojocky/node-pdfium-native#9]
Hi I downloaded the node-pdfium zip and extracted the package. The "noge-gyp configure" command run successfully in the root folder but while building the project using command "node-gyp build" it throw the following error and warning:-

``` console
C:\Users\xz\Downloads\node-pdfium-master>node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.2.1
gyp info using node@0.12.7 | win32 | ia32
gyp info spawn C:\Program Files\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFram
eworkVersion or PlatformToolset may be set to an invalid version number. [C:\Users\xz\Downloads\node-pdfium-master\build\third_party\pdfium\third_party\bigint.vcxproj]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MSB6006: "CL.exe" exited with code -1073741515. [C:\Users\xz\Downloads\node-pd
fium-master\build\third_party\pdfium\third_party\bigint.vcxproj]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFram
eworkVersion or PlatformToolset may be set to an invalid version number. [C:\Users\xz\Downloads\node-pdfium-master\build\third_party\pdfium\fdrm.vcxproj]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MSB6006: "CL.exe" exited with code -1073741515. [C:\Users\xz\Downloads\node-pd
fium-master\build\third_party\pdfium\fdrm.vcxproj]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFram
eworkVersion or PlatformToolset may be set to an invalid version number. [C:\Users\xz\Downloads\node-pdfium-master\build\third_party\pdfium\formfiller.vcxproj]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MSB6006: "CL.exe" exited with code -1073741515. [C:\Users\xz\Downloads\node-pd
fium-master\build\third_party\pdfium\formfiller.vcxproj]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFram
eworkVersion or PlatformToolset may be set to an invalid version number. [C:\Users\xz\Downloads\node-pdfium-master\build\third_party\pdfium\fpdfapi.vcxproj]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MSB6006: "CL.exe" exited with code -1073741515. [C:\Users\xz\Downloads\node-pd
fium-master\build\third_party\pdfium\fpdfapi.vcxproj]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFram
eworkVersion or PlatformToolset may be set to an invalid version number. [C:\Users\xz\Downloads\node-pdfium-master\build\third_party\pdfium\fpdfdoc.vcxproj]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MSB6006: "CL.exe" exited with code -1073741515. [C:\Users\xz\Downloads\node-pd
fium-master\build\third_party\pdfium\fpdfdoc.vcxproj]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFram
eworkVersion or PlatformToolset may be set to an invalid version number. [C:\Users\xz\Downloads\node-pdfium-master\build\third_party\pdfium\fpdftext.vcxproj]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MSB6006: "CL.exe" exited with code -1073741515. [C:\Users\xz\Downloads\node-pd
fium-master\build\third_party\pdfium\fpdftext.vcxproj]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFram
eworkVersion or PlatformToolset may be set to an invalid version number. [C:\Users\xz\Downloads\node-pdfium-master\build\third_party\pdfium\third_party\freetype.vcxproj]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MSB6006: "CL.exe" exited with code -1073741515. [C:\Users\xz\Downloads\node-pd
fium-master\build\third_party\pdfium\third_party\freetype.vcxproj]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFram
eworkVersion or PlatformToolset may be set to an invalid version number. [C:\Users\xz\Downloads\node-pdfium-master\build\fx_lpng.vcxproj]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MSB6006: "CL.exe" exited with code -1073741515. [C:\Users\xz\Downloads\node-pd
fium-master\build\fx_lpng.vcxproj]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFram
eworkVersion or PlatformToolset may be set to an invalid version number. [C:\Users\xz\Downloads\node-pdfium-master\build\third_party\pdfium\fxcodec.vcxproj]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MSB6006: "CL.exe" exited with code -1073741515. [C:\Users\xz\Downloads\node-pd
fium-master\build\third_party\pdfium\fxcodec.vcxproj]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFram
eworkVersion or PlatformToolset may be set to an invalid version number. [C:\Users\xz\Downloads\node-pdfium-master\build\third_party\pdfium\fxcrt.vcxproj]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MSB6006: "CL.exe" exited with code -1073741515. [C:\Users\xz\Downloads\node-pd
fium-master\build\third_party\pdfium\fxcrt.vcxproj]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFram
eworkVersion or PlatformToolset may be set to an invalid version number. [C:\Users\xz\Downloads\node-pdfium-master\build\third_party\pdfium\fxedit.vcxproj]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MSB6006: "CL.exe" exited with code -1073741515. [C:\Users\xz\Downloads\node-pd
fium-master\build\third_party\pdfium\fxedit.vcxproj]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFram
eworkVersion or PlatformToolset may be set to an invalid version number. [C:\Users\xz\Downloads\node-pdfium-master\build\third_party\pdfium\fxge.vcxproj]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MSB6006: "CL.exe" exited with code -1073741515. [C:\Users\xz\Downloads\node-pd
fium-master\build\third_party\pdfium\fxge.vcxproj]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFram
eworkVersion or PlatformToolset may be set to an invalid version number. [C:\Users\xz\Downloads\node-pdfium-master\build\third_party\pdfium\javascript.vcxproj]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MSB6006: "CL.exe" exited with code -1073741515. [C:\Users\xz\Downloads\node-pd
fium-master\build\third_party\pdfium\javascript.vcxproj]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFram
eworkVersion or PlatformToolset may be set to an invalid version number. [C:\Users\xz\Downloads\node-pdfium-master\build\third_party\pdfium\jsapi.vcxproj]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MSB6006: "CL.exe" exited with code -1073741515. [C:\Users\xz\Downloads\node-pd
fium-master\build\third_party\pdfium\jsapi.vcxproj]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFram
eworkVersion or PlatformToolset may be set to an invalid version number. [C:\Users\xz\Downloads\node-pdfium-master\build\third_party\pdfium\third_party\pdfium_base.vcxpr
oj]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFram
eworkVersion or PlatformToolset may be set to an invalid version number. [C:\Users\xz\Downloads\node-pdfium-master\build\third_party\pdfium\pdfwindow.vcxproj]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MSB6006: "CL.exe" exited with code -1073741515. [C:\Users\xz\Downloads\node-pd
fium-master\build\third_party\pdfium\pdfwindow.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\xz\AppData\Roaming\nvm\v0.12.7\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd C:\Users\xz\Downloads\node-pdfium-master
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok

C:\Users\xz\Downloads\node-pdfium-master>
                                                                                                                               
```

One more thing I need to ask is weather to build this project using **node-gyp** or via **nw-gyp** because I want to use this plugin in node-webkit.

**Comment by josecols** [comment]
+1

**Comment by dhenson02** [comment]
+1
